# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-SmallProf
version:      1.14
version_from: SmallProf.pm
installdirs:  site
requires:
    Time::HiRes:                   1.20

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
